--- 
- hosts: local 
  remote_user: kash296
  become: yes
    # become_method: sudo
  tasks:
    - name: Build Docker image from Dockerfile
      docker_image:
        name: twitter_bot
        path: /var/lib/jenkins/workspace/TwitterBot Phase 1/
        state: present
    
    - name: Remove Docker container after tweet
      docker_image:
        name: twitter_bot
        path: /var/lib/jenkins/workspace/TwitterBot Phase 1/
        state: absent    

