--- 
- hosts: local 
  remote_user: kash296
  become: yes
    # become_method: sudo
  tasks:
    - name: Build Docker image from Dockerfile
      docker_image:
        name: twitter_bot
        path: /home/kash296/Programs/Python Programs/kash296twitbot
        state: present
    
    - name: Remove Docker container after tweet
      docker_image:
        name: twitter_bot
        path: /home/kash296/Programs/Python Programs/kash296twitbot
        state: absent    

